import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/PageHeader";

export const Route = createFileRoute("/business-model")({
  head: () => ({
    meta: [
      { title: "Business Model — Surf & Wellness Community" },
      { name: "description", content: "SWC operates third-party assets through management agreements, lease and sublease contracts, generating revenue from commissions, management fees, revenue sharing and operations." },
      { property: "og:title", content: "Business Model — Surf & Wellness Community" },
      { property: "og:description", content: "Asset-light operating model based on third-party property management and intermediation." },
    ],
  }),
  component: BusinessModelPage,
});

function BusinessModelPage() {
  return (
    <>
      <PageHeader
        eyebrow="Business Model"
        title="Asset-light. Contract-based. Revenue from services and operations."
        intro="SWC does not initially own real estate. The group generates revenue exclusively from professional services, intermediation and the operation of properties owned by third parties."
      />

      <section className="container-prose py-20">
        <div className="grid md:grid-cols-12 gap-10">
          <div className="md:col-span-5">
            <div className="eyebrow">How we work</div>
            <h2 className="mt-3 text-3xl md:text-4xl leading-tight">
              Three contractual frameworks govern every relationship.
            </h2>
          </div>
          <div className="md:col-span-7 space-y-8">
            {[
              { n: "01", t: "Brokerage mandates", c: "Signed with property owners or investors for the purchase or sale of specific assets. SWC is remunerated through a transaction commission upon closing." },
              { n: "02", t: "Management agreements", c: "Signed with property owners. SWC operates the asset on the owner's behalf and is remunerated through a management fee and/or revenue sharing." },
              { n: "03", t: "Lease & sublease contracts", c: "SWC leases properties from owners and re-commercializes them through short or mid-term sublease, retaining the operating margin." },
            ].map((i) => (
              <div key={i.n} className="flex gap-6 border-t border-border pt-6">
                <div className="font-display text-3xl text-muted-foreground w-12">{i.n}</div>
                <div>
                  <h3 className="text-xl">{i.t}</h3>
                  <p className="mt-2 text-muted-foreground leading-relaxed">{i.c}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="border-t border-border bg-secondary/40">
        <div className="container-prose py-20">
          <div className="eyebrow">Revenue streams</div>
          <h2 className="mt-3 text-3xl md:text-4xl">How the company generates income</h2>
          <div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-5 gap-6">
            {[
              ["Brokerage commissions", "Fees received from property owners or buyers upon completion of real estate transactions."],
              ["Management fees", "Recurring fees received from owners for the operational management of their accommodations."],
              ["Revenue sharing", "Variable participation on net operating revenue generated by managed properties."],
              ["Accommodation operations", "Direct income from guest stays at properties operated under lease or sublease agreements."],
              ["Guest services", "Ancillary income from services provided to guests during their stay."],
            ].map(([t, c]) => (
              <div key={t} className="bg-background border border-border p-6">
                <div className="rule mb-4" />
                <div className="font-medium">{t}</div>
                <p className="mt-2 text-sm text-muted-foreground leading-relaxed">{c}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="container-prose py-20">
        <div className="eyebrow">Counterparties &amp; flows</div>
        <h2 className="mt-3 text-3xl md:text-4xl max-w-3xl">Clear, traceable flows between identified parties.</h2>
        <div className="mt-10 grid md:grid-cols-3 gap-8 text-sm">
          {[
            { t: "Inflows", items: ["Property owners (management fees, revenue sharing)", "Buyers and sellers (brokerage commissions)", "Hospitality guests (room and service revenue, via licensed payment processors)"] },
            { t: "Outflows", items: ["Local subsidiaries and service providers", "Owner distributions under management agreements", "Operating expenses, salaries, taxes and statutory obligations"] },
            { t: "Documentation", items: ["Signed contracts with each counterparty", "Invoices and accounting records per jurisdiction", "Periodic financial reporting to owners"] },
          ].map((b) => (
            <div key={b.t} className="border-t border-foreground pt-5">
              <div className="eyebrow">{b.t}</div>
              <ul className="mt-4 space-y-2 text-foreground/80">
                {b.items.map((x) => <li key={x}>· {x}</li>)}
              </ul>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}
