/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueRouteImport } from './routes/value'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GlobalPresenceRouteImport } from './routes/global-presence'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessModelRouteImport } from './routes/business-model'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ValueRoute = ValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPresenceRoute = GlobalPresenceRouteImport.update({
  id: '/global-presence',
  path: '/global-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModelRoute = BusinessModelRouteImport.update({
  id: '/business-model',
  path: '/business-model',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/legal': typeof LegalRoute
  '/services': typeof ServicesRoute
  '/value': typeof ValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/legal': typeof LegalRoute
  '/services': typeof ServicesRoute
  '/value': typeof ValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/legal': typeof LegalRoute
  '/services': typeof ServicesRoute
  '/value': typeof ValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/global-presence'
    | '/legal'
    | '/services'
    | '/value'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/global-presence'
    | '/legal'
    | '/services'
    | '/value'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/global-presence'
    | '/legal'
    | '/services'
    | '/value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessModelRoute: typeof BusinessModelRoute
  ContactRoute: typeof ContactRoute
  GlobalPresenceRoute: typeof GlobalPresenceRoute
  LegalRoute: typeof LegalRoute
  ServicesRoute: typeof ServicesRoute
  ValueRoute: typeof ValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value': {
      id: '/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof ValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-presence': {
      id: '/global-presence'
      path: '/global-presence'
      fullPath: '/global-presence'
      preLoaderRoute: typeof GlobalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-model': {
      id: '/business-model'
      path: '/business-model'
      fullPath: '/business-model'
      preLoaderRoute: typeof BusinessModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessModelRoute: BusinessModelRoute,
  ContactRoute: ContactRoute,
  GlobalPresenceRoute: GlobalPresenceRoute,
  LegalRoute: LegalRoute,
  ServicesRoute: ServicesRoute,
  ValueRoute: ValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
